version: '3.7'
services:        
    local-mongo:
            build:
                context: ./
                dockerfile: deploy/mongo/Dockerfile
            image: local-mongo
            restart: always
            container_name: local-mongo-c
            volumes:
                    - /home/developer/volumes/mongo/db_data:/data/db
            ports:
                    - "${MONGO_PORT}:27017"
